// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/tikasan/goa-simple-sample/design
// --out=$(GOPATH)/src/github.com/tikasan/goa-simple-sample
// --version=v1.1.0
//
// API "goa simple sample": accounts Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// ListAccountsPath computes a request path to the list action of accounts.
func ListAccountsPath() string {

	return fmt.Sprintf("/api/v1/accounts/users")
}

// アカウント（複数）
func (c *Client) ListAccounts(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListAccountsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListAccountsRequest create the request corresponding to the list action endpoint of the accounts resource.
func (c *Client) NewListAccountsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowAccountsPath computes a request path to the show action of accounts.
func ShowAccountsPath(id string) string {
	param0 := id

	return fmt.Sprintf("/api/v1/accounts/users/%s", param0)
}

// アカウント（単数）
func (c *Client) ShowAccounts(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowAccountsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowAccountsRequest create the request corresponding to the show action endpoint of the accounts resource.
func (c *Client) NewShowAccountsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
