// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/tikasan/goa-simple-sample/design
// --out=$(GOPATH)/src/github.com/tikasan/goa-simple-sample
// --version=v1.1.0
//
// API "goa simple sample": view Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// ViewViewPath computes a request path to the view action of view.
func ViewViewPath() string {

	return fmt.Sprintf("/api/v1/view/default")
}

// ViewViewPath2 computes a request path to the view action of view.
func ViewViewPath2() string {

	return fmt.Sprintf("/api/v1/view/tiny")
}

// MediaTypeのバリエーション
func (c *Client) ViewView(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewViewViewRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewViewViewRequest create the request corresponding to the view action endpoint of the view resource.
func (c *Client) NewViewViewRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
