db:
  build: .
  container_name: celler
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: celler
    MYSQL_USER: celler
    MYSQL_PASSWORD: celler
    TZ: "Asia/Tokyo"
  ports:
  - "3306:3306"
