// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "goa simple sample": js TestHelpers
//
// Command:
// $ goagen
// --design=github.com/tikasan/goa-simple-sample/design
// --out=$(GOPATH)/src/github.com/tikasan/goa-simple-sample
// --version=v1.2.0-dirty

package test
