// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "goa simple sample": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/pei0804/goa-simple-sample/design
// --out=$(GOPATH)/src/github.com/pei0804/goa-simple-sample
// --version=v1.2.0-dirty

package test
